/***** JOIN 실습 *****/

--1. EMPLOYEE 테이블과 DEPARTMENT 테이블을 조인해서
-- 각 직원의 이름과 그 직원이 속한 부서명 조회

--ANSI
SELECT EMP_NAME, DEPT_TITLE
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID);

--ORACLE
SELECT EMP_NAME, DEPT_TITLE
FROM EMPLOYEE, DEPARTMENT
WHERE DEPT_CODE = DEPT_ID;

--2. EMPLOYEE 테이블과 DEPARTMENT 테이블을 조인해서
-- 각 직원의 이름과 그 직원이 속한 부서명, 급여 조회

--ANSI
SELECT EMP_NAME, DEPT_TITLE, SALARY
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID);

--ORACLE
SELECT EMP_NAME, DEPT_TITLE, SALARY
FROM EMPLOYEE, DEPARTMENT
WHERE DEPT_CODE = DEPT_ID;


--3. EMPLOYEE 테이블과 SAL_GRADE 테이블을 조인해서
--각 직원의 이름과 급여 등급 조회
SELECT * FROM EMPLOYEE;
SELECT * FROM SAL_GRADE;
--ANSI
SELECT EMP_NAME, SAL_GRADE. SAL_LEVEL
FROM EMPLOYEE
JOIN SAL_GRADE ON (EMPLOYEE. SAL_LEVEL = SAL_GRADE. SAL_LEVEL);
/*
다른 테이블에서 컬럼명은 다르지만 서로 의미하는 바가 같은 컬럼끼리는
컬럼명1 = 컬럼명A 사용할 수 있음

다른 테이블에서 컬럼명이 같을 때는 참조하는 테이블이 무엇인지 작성해줘야 함
테이블명.컬럼명1 = 테이블명.컬럼명2
SELECT로 참조할 때도 테이블명 작성해서 어디서 어느칼럼을 가지고오는지 작성
*/

--ORACLE
SELECT e.EMP_NAME, s. SAL_LEVEL
FROM EMPLOYEE e, SAL_GRADE s
WHERE e.SAL_LEVEL = s. SAL_LEVEL;


--각 직원의 이름과 그 직원이 속한 부서의 부서명 및 직급 조회
--테이블 EMPLOYEE  DEPARTMENT  JOB

--ANSI
SELECT e.EMP_NAME, d. DEPT_TITLE, j. JOB_CODE
FROM EMPLOYEE e
JOIN DEPARTMENT d ON (e.DEPT_CODE = d.DEPT_ID)
JOIN  JOB j ON (e.JOB_CODE = j.JOB_CODE);

SELECT * FROM JOB;
/*
EMPLOYEE    DEPARTMENT        JOB
EMP_NAME    DEPT_TITLE      JOB_CODE
전지연	       인사관리부	        J6
차태연	       인사관리부	        J6
방명수	       인사관리부	        J7
*/

--ORACLE
SELECT e.EMP_NAME, d.DEPT_TITLE, j.JOB_CODE
FROM EMPLOYEE e, DEPARTMENT d, JOB j
WHERE e.DEPT_CODE = d.DEPT_ID
AND e.JOB_CODE = j.JOB_CODE;


--1. 직원의 이메일 주소와 해당 부서의 부서명 조회
--TABLE : EMPLOYEE DEPARTMENT
--SELECT EMAIL  DEPT_TITLE
SELECT e.EMAIL, d.DEPT_TITLE
FROM EMPLOYEE e, DEPARTMENT d
WHERE e.DEPT_CODE = d.DEPT_ID;

--2. 급여가 300만원 이상인 직원들의 이름과 그 직원이 속한 부서명 조회
--TABLE : EMPLOYEE. DEPARTMENT
--SELECT EMP_NAME, DEPT_TITLE
--WHERE
SELECT e.EMP_NAME, d.DEPT_TITLE, SALARY
FROM EMPLOYEE e, DEPARTMENT d
WHERE e.DEPT_CODE = d.DEPT_ID
AND SALARY >=3000000;

--3. 각 직원의 이름과 그 직원이 속한 부서명의 부서명, 급여등급명 조회
--TABLE : EMPLOYEE, DEPARTMENT, SAL_GRADE
--SELECT : EMP_NAME, DEPT_TITLE, SAL_LEVEL
SELECT e.EMP_NAME, d.DEPT_TITLE, s.SAL_LEVEL
FROM EMPLOYEE e, DEPARTMENT d, SAL_GRADE s
WHERE e.DEPT_CODE = d.DEPT_ID
AND e.SAL_LEVEL = s.SAL_LEVEL;

--4. 직급이 대리이면서 아시아 지역에 근무하는 직원 조회
-- 사번 이름 직급명 부서명 근무지역명 급여를 조회
--EMPLOYEE, JOB, DEPARTMENT, LOCATION
SELECT e.EMP_ID, e.EMP_NAME, j.JOB_NAME, d.DEPT_TITLE, l.LOCAL_NAME, e.SALARY
FROM EMPLOYEE e, JOB j, DEPARTMENT d, LOCATION l
WHERE e.DEPT_CODE = d.DEPT_ID
AND e.JOB_CODE = j.JOB_CODE
AND d.LOCATION_ID = l. LOCAL_CODE
AND JOB_NAME = '대리' AND LOCAL_NAME LIKE 'ASIA%';




--1. D5 부서에 속한 직원들의 이름과 직급명 조회
--테이블 EMPLOYEE JOB
SELECT e.EMP_NAME, j.JOB_NAME
FROM EMPLOYEE e, JOB j
WHERE e.JOB_CODE = j.JOB_CODE
AND e.DEPT_CODE = 'D5';
--2. 각 부서의 부서명과 해당 부서에 속한 직원의 평균급여 조회
--테이블 EMPLOYEE DEPARTMENT
---GROUP BY
---AVG

SELECT d.DEPT_TITLE, FLOOR(AVG(e.SALARY))
FROM DEPARTMENT d, EMPLOYEE e
WHERE d.DEPT_ID = e.DEPT_CODE
GROUP BY d.DEPT_TITLE;


--3. 급여 등급이 S4 이상인 직원의 이름, 급여, 급여 등급 조회
--SELECT * FROM SAL_GRADE
--테이블 EMPLOYEE SAL_GRADE
---WHERE IN
SELECT e.EMP_NAME, e.SALARY, s.SAL_LEVEL
FROM EMPLOYEE e, SAL_GRADE s
WHERE e.SAL_LEVEL = s.SAL_LEVEL
AND e.SAL_LEVEL IN ('S4', 'S5', 'S6');
















